config/routes.rb
Rails.application.routes.draw do
  get 'lending/index'
  resources :categories
  devise_for :users
  resources :subscribers
  resources :posts do
    resources :comments
    resources :likes
    resources :favorites
  end
  get 'about/index'
  get 'promo/index'
  get 'posts/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'lending', to: 'lending#index'

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show', :as => :user
  delete 'users/:id', to: 'users#destroy'


  root 'lending#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
		validates :author, :presence => true
    validates :tag, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }
    has_many :comments, :dependent => :destroy
		has_many :favorites, dependent: :destroy
		mount_uploader :image, ImageForPostsUploader
		belongs_to :user

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commenter, :body).merge(user_id: current_user.id))
		redirect_to post_path(@post)
	end
  def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/lending_controller.rb
class LendingController < ApplicationController
  layout "lending"
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
    else
      @posts = Post.all
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
  @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:author, :title, :content, :image, :category_id)
    end
end

app/controllers/promo_controller.rb
class PromoController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    if @user
      @posts = @user.favorited_posts
      render actions: :show
      @favorites = @user.favorites.all
    else
        render file: 'public/404', status: 404, formats: [:html]
    end
  end

def favorited?(post)
    favorites.find_by(post_id: post.id).present?
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lending_helper.rb
module LendingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
		<tr>
			<p>
  			<b>Commenter:</b>
  			<%= User.find(comment.user_id).email %>
			</p>
			<td><%= comment.commenter %></td>
			<td><%= comment.body %></td>
			<%# <%= @post.comments.inspect %> %>
			<td><button class="image_button" type="button" name="button">
				<%= link_to image_tag("delete.svg"), [comment.post, comment],
										:confirm => 'Удалить?',
										:method => :delete %>
					</button></td>
		</tr>
		<% if user_signed_in? && current_user.id == comment.user_id  %>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="field">
		<%= f.text_field :commenter, placeholder: "имя" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "комментарий" %>
	</div>
	<div class="field">
    <%= current_user.email %>
	</div>
		<div class="actions">
			<button type="button" name="button">
	        <%= link_to 'отправить', "#", onclick: "this.closest('form').submit();return false" %>
	    </button>
	</div>
<% end %>

app/views/posts/_form.html.erb
<%= stylesheet_link_tag "posts" %>
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table>
  <tr>
    <td><%= form.label :author, "автор" %></td>
    <td><%= form.text_field :author %></td>
  </tr>
  <tr>
    <td> <%= form.label :category_id %></td>
    <td> <%= form.select :category_id, Category.pluck(:name, :id) %></td>
  </tr>
  <tr>
    <td><%= form.label :title, "заголовок" %></td>
    <td><%= form.text_field :title %></td>
  </tr>
  <tr>
    <td><%= form.label :content, "контент" %></td>
    <td><%= form.text_area :content %></td>
  </tr>
  <tr>
    <td><%= form.label :image, "добавить изображение" %></td>
    <td><button type="button" name="button"><%= form.file_field :image %></button></td>
  </tr>
</table>


  <div class="actions">
    <button type="button" name="button">
        <%= link_to 'сохранить', "#", onclick: "this.closest('form').submit();return false" %>
    </button>
    <button type="button" name="button">
      <%= link_to 'Назад', posts_path %>
    </button>
    
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag "posts" %>
<div class="conteiner">

<h1>Редактирование записи</h1>

<%= render 'form', post: @post %>


</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "posts" %>
<p id="notice"><%= notice %></p>
<div class="conteiner">

<h1>Записи на форуме</h1>

<h2>Фильтр</h2>
<% Category.all.each do |cat| %>
	<%= link_to cat.name, posts_path(category: cat.name) %> <br>
<% end %>
<button class="newpost_btn" type="button" name="button">
  <%= link_to 'Категории', categories_path %>
</button>

<button class="newpost_btn" type="button" name="button">
<%= link_to 'Новая запись', new_post_path %>
</button>
<!-- <button class="about_btn" type="button" name="button"><%= link_to 'О проекте', about_path %></button> -->

<table>
  <thead>
    <tr>
      <th>Автор</th>
      <th>Тема</th>
      <th>Заголовок</th>
      <!-- <th>Контент</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.author %></td>
        <td><%= post.tag %></td>
        <td><%= post.title %></td>
        <!-- <td><%= post.content %></td> -->
        <td><button type="button" name="button" class="image_button"><%= link_to 'Показать', post %></button></td>
        <td><button type="button" name="button" class="image_button"><%= link_to image_tag("edit.svg"), edit_post_path(post) %></button></td>
        <td><button type="button" name="button" class="image_button"><%= link_to image_tag("delete.svg"), post, method: :delete, data: { confirm: 'Удалить?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<button type="button" name="button">
	<%= link_to 'О проекте', lending_path %>
</button>


</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "posts" %>
<div class="conteiner">
<h1>Новая запись</h1>

<%= render 'form', post: @post %>

</div>
 

app/views/posts/show.html.erb
<%= stylesheet_link_tag "posts" %>
<div class="conteiner">
<h1>Запись</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <td><strong>Автор:</strong></td>
    <td>  <%= @post.author %></td>
  </tr>
  <tr>
    <td><strong>Тема:</strong></td>
    <td>  <%= @post.tag %></td>
  </tr>
  <tr>
    <td>  <strong>Заголовок:</strong></td>
    <td><%= @post.title %></td>
  </tr>
  <tr>
    <td><strong>Контент:</strong></td>
    <td>  <%= @post.content %></td>
    <td><%= image_tag(@post.image.url, alt: 'ImageForPosts', class:"image_for_post") if @post.image? %></td>
  </tr>
</table>
<% pre_favorite = @post.favorites.find { |favorite| favorite.user_id == current_user.id} %>
<% if pre_favorite %>
    <%= button_to 'Remove from Favorite', post_favorite_path(@post, pre_favorite), method: :delete %>
<% else %>
    <%= button_to 'Add to Favorite', post_favorites_path(@post), method: :post %>
<% end %>



<h2>Комментарии:</h2>


<% if user_signed_in? %>
<%= render "comments/form" %>
<% else %>
<p>Please <%= link_to 'login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to comment.</p>
<% end %>
<table>
  <tr>
    <th><b>Автор:</b></th>
    <th><b>Комментарий:</b></th>

  </tr>
  <%= render @post.comments.select(&:persisted?) %>

  </table>


<button type="button" name="button">
  <% if user_signed_in? %>
  <%= link_to 'Редактировать', edit_post_path(@post) %>
  <% end %>
</button>
<button type="button" name="button"><%= link_to 'Назад', posts_path %></button>

</div>

app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Username</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, user %></td>
        <td><%= user.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>ID <%= @user.id %></p>
<p>Email <%= @user.email %></p>
<p>Username <%= @user.username %></p>
<% if user_signed_in? && @user.id == current_user.id %>
	<p><%= link_to 'Edit profile', edit_user_registration_path %></p>
<% end %>
In favorites <%= @user.favorites.count %> <%= (@user.favorites.count) == 1 ? 'Post' : 'Posts'%>
<% @posts.each do |post| %>
  <br><%= link_to post.title, post %>
<% end %>